name: Build & Deploy 🚀

env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
   push:
      branches: ['master']

jobs:
   DeployOnVercel:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Install dependencies
           run: yarn install --frozen-lockfile

         - name: Build
           run: yarn run build

         - name: Install Vercel CLI
           run: yarn global add vercel

         - name: Pull Vercel Environment Information
           run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

         - name: Build Project Artifacts
           run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

         - name: Deploy Project Artifacts to Vercel
           run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
